import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 414, height: 896 }, deviceScaleFactor: 1 })
await page.goto('http://localhost:5173/?reset=1')
await page.waitForFunction(() => window.__kurioMock)
await page.goto('http://localhost:5173/nfts/emerald-ape-042')
await page.waitForFunction(() => window.__kurioMock)
await page.getByRole('heading', { name: 'Emerald Ape #042' }).waitFor()
await page.waitForTimeout(800)
await page.screenshot({ path: process.env.TEMP + '/claude/mobile-detail-before.png', fullPage: true })
await browser.close()
