/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountWalletsRouteImport } from './routes/account/wallets'
import { Route as NftsNftIdRouteImport } from './routes/nfts/$nftId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as ExplorerTxHashRouteImport } from './routes/explorer/tx/$hash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWalletsRoute = AccountWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AccountRoute,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerTxHashRoute = ExplorerTxHashRouteImport.update({
  id: '/explorer/tx/$hash',
  path: '/explorer/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/account/': typeof AccountIndexRoute
  '/explorer/tx/$hash': typeof ExplorerTxHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/account': typeof AccountIndexRoute
  '/explorer/tx/$hash': typeof ExplorerTxHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/account/': typeof AccountIndexRoute
  '/explorer/tx/$hash': typeof ExplorerTxHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/account/profile'
    | '/account/wallets'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/account/'
    | '/explorer/tx/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/account/profile'
    | '/account/wallets'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/account'
    | '/explorer/tx/$hash'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/account/profile'
    | '/account/wallets'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/account/'
    | '/explorer/tx/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ExplorerTxHashRoute: typeof ExplorerTxHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wallets': {
      id: '/account/wallets'
      path: '/wallets'
      fullPath: '/account/wallets'
      preLoaderRoute: typeof AccountWalletsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/tx/$hash': {
      id: '/explorer/tx/$hash'
      path: '/explorer/tx/$hash'
      fullPath: '/explorer/tx/$hash'
      preLoaderRoute: typeof ExplorerTxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWalletsRoute: typeof AccountWalletsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountWalletsRoute: AccountWalletsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  NftsNftIdRoute: NftsNftIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ExplorerTxHashRoute: ExplorerTxHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
